// <auto-generated />
using System;
using KartOrderService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KartOrderService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    partial class OrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KartOrderService.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("PaymentIntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_intent_id");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("TrackingId")
                        .HasColumnType("text")
                        .HasColumnName("tracking_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("OrderId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("idx_orders_idempotency_key");

                    b.HasIndex("TrackingId")
                        .HasDatabaseName("idx_orders_tracking_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_orders_user_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_orders_status_created");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("KartOrderService.Infrastructure.Auditing.OrderAuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_type");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_name");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("idx_order_audit_log_entity");

                    b.ToTable("order_audit_log", (string)null);
                });

            modelBuilder.Entity("KartOrderService.Domain.Orders.Order", b =>
                {
                    b.OwnsMany("KartOrderService.Domain.Orders.OrderEvent", "Events", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by");

                            b1.Property<string>("EventType")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("event_type");

                            b1.Property<string>("FromStatus")
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("from_status");

                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("order_id");

                            b1.Property<string>("Payload")
                                .HasColumnType("jsonb")
                                .HasColumnName("payload");

                            b1.Property<DateTimeOffset?>("ProjectedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("projected_at");

                            b1.Property<DateTimeOffset?>("PublishedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("published_at");

                            b1.Property<int>("Sequence")
                                .HasColumnType("integer")
                                .HasColumnName("sequence");

                            b1.Property<string>("ToStatus")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("to_status");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("updated_by");

                            b1.HasKey("Id");

                            b1.HasIndex("CreatedAt")
                                .HasDatabaseName("idx_outbox_unpublished")
                                .HasFilter("event_type IS NOT NULL AND published_at IS NULL");

                            b1.HasIndex("OrderId", "Sequence")
                                .IsUnique()
                                .HasDatabaseName("idx_order_events_order_seq");

                            b1.ToTable("order_events", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsMany("KartOrderService.Domain.Orders.OrderLineItem", "LineItems", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("currency");

                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("order_id");

                            b1.Property<int>("Qty")
                                .HasColumnType("integer")
                                .HasColumnName("qty");

                            b1.Property<DateTimeOffset?>("ReservationConfirmedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("reservation_confirmed_at");

                            b1.Property<Guid?>("ReservationId")
                                .HasColumnType("uuid")
                                .HasColumnName("reservation_id");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("sku");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("unit_price");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("updated_by");

                            b1.HasKey("Id");

                            b1.HasIndex("OrderId")
                                .HasDatabaseName("idx_order_items_order_id");

                            b1.ToTable("order_items", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Events");

                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
